### ISSUE TITLE
The repository is not updated anymore

### ISSUE THREAD

**Issue by blastrock** [gnthibault/siril#2]
Hello,

I'm new on Siril and I wanted to compile it myself (with libraw's latest beta to support my Canon R7's CR3 files).

I noticed that the last commit 5a77075076b8cc4265639d5c5d8f87508c9c20d9 dates from 11 months ago. Can you update this repository with the latest code?

EDIT: I just found that the code is distributed on the main site, still I think it would be nice to have this repository up to date. People (maybe me!) may want to make pull requests.

**Comment by marcellobarile** [comment]
I wanted to contribute but then stumbled upon this message... now I'm confused :D @gnthibault any hint?

**Comment by marcellobarile** [comment]
EDIT: I've found what seems to be the updated one on GitLab https://gitlab.com/free-astro/siril - an official confirm would be nice though.

**Comment by gnthibault** [comment]
Dear all, I am very sorry for you all. I confirm the official repository is  https://gitlab.com/free-astro/siril 
This was a simply a small attempt from my side some years ago to build support for GPU-enabled high performance stacking, starting by implementing CMake based build system.
But at the time, the state of the source code was clearly not ready for this (too much entanglement between frontend and backend).

I need to get back at it, I am sure it evolved a lot in the past few years.
Sorry for the confusing repository. Best regards
